class InstantiatedCharacter():
    def __init__(self, tupple):
        self.id = tupple[0]
        self.base_id = tupple[1]
        self.base_name = tupple[2]
        self.owner = tupple[3]
        self.name = tupple[4]
        self.named = tupple[5]
        self.series = tupple[6]
        self.rarity = tupple[7]
        self.type = tupple[8]
        self.level = tupple[9]
        self.exp = tupple[10]
        self.max_health = tupple[11]
        self.max_mana = tupple[12]
        self.armor = tupple[13]
        self.attack = tupple[14]
        self.image = tupple[15]